[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "14.15.3", RUBY_VERSION = "2.7.1" }

[context.deploy-preview]
  environment = { NODE_VERSION = "14.15.3", RUBY_VERSION = "2.7.1" }

[dev]
  command = "npm run dev"
  publish = "build"
  port = 3000
  targetPort = 8080
  framework = "#custom"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://pcards.netlify.app https://api.netlify.com; style-src 'self' https://pcards.netlify.app 'unsafe-inline'; script-src https://identity.netlify.app https://unpkg.com 'self' 'unsafe-eval' 'unsafe-inline'; worker-src 'self' blob:;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
